---
- name: Download Opera GX installer
  win_get_url:
    url: "https://download3.operacdn.com/pub/opera_gx/desktop/83.0.4254.27/win/Opera_GX_83.0.4254.27_Setup.exe"
    dest: "C:\\Temp\\OperaGX_Setup.exe"

- name: Install Opera GX
  win_command: "C:\\Temp\\OperaGX_Setup.exe /silent /install"
  ignore_errors: yes
  register: install_result
  until: install_result is succeeded
  retries: 3

- name: Check if Opera GX is installed
  win_stat:
    path: "C:\\Program Files\\Opera GX\\launcher.exe"
  register: operagx_installed

- name: Fail if Opera GX installation failed
  fail:
    msg: "Opera GX installation failed."
  when: install_result is failed or not operagx_installed.stat.exists
