---
- name: Download Opera GX executable
  win_command: |
    Invoke-WebRequest -Uri "https://ftp.opera.com/pub/opera/desktop/108.0.5067.40/win/Opera_108.0.5067.40_Setup.exe" -OutFile "C:\Temp\OperaGX_Setup.exe"

- name: Install Opera GX
  win_command: |
    C:\Temp\OperaGX_Setup.exe /silent /install
