---
- name: Create desktop shortcut
  win_shell: |
    $url = "{{ udemy_url }}"
    $shortcutPath = "$env:PUBLIC\Desktop\Udemy.lnk"
        
    $WshShell = New-Object -ComObject WScript.Shell
    $Shortcut = $WshShell.CreateShortcut($shortcutPath)
        
    $Shortcut.TargetPath = $url
    $Shortcut.IconLocation = "C:\Windows\System32\imageres.dll, 14"  # Icon for the shortcut (you can change it)
    $Shortcut.Description = "Udemy Website"
    $Shortcut.Save()
